### ISSUE TITLE
template ethernet_RedHat.j2 : bootproto set at none instead of static

### ISSUE THREAD

**Issue by dginhoux** [michaelrigart/ansible-role-interfaces#110]
Hi, 

I've just found an error on the template ethernet_RedHat.j2 of the current version 1.11.1 and on the master branch.
At line 9, `bootproto` must be set at `static` and not `none`.

must be : 
```
...
{% if item.bootproto == 'static' %}
BOOTPROTO=static
...
```

**Comment by guegrer** [comment]
got the same trouble... with redhat

**Comment by dginhoux** [comment]
I made a mistake, none and static are quite equivalent after reading the RHEL documentation.
The better way is : https://access.redhat.com/solutions/8627

It's not `BOOTPROTO` directive problem, this solution put `NOZEROCONF=yes` in the `/etc/sysconfig/network`. It can be added on each interface too and it work fine.
