### ISSUE TITLE
Bridge configuration can cause loss of connectivity

### ISSUE THREAD

**Issue by markgoddard** [michaelrigart/ansible-role-interfaces#12]
In some cases we might find that bouncing a bridge interface separately from its ports can cause us to lose connectivity. This might be because the bridge is being an assigned an IP that was previously assigned to one of the ports, or because bringing up the bridge adds a default route that is not accessible while the ports are inactive or detached from the bridge.

To overcome this limitation, the bridge and its ports should be bounced (ifdown/ifup) in a single task.

**Comment by michaelrigart** [comment]
Thank you for the report en PR. This has been merged
