### ISSUE TITLE
Introduce tags for versioning

### ISSUE THREAD

**Issue by layereight** [michaelrigart/ansible-role-interfaces#34]
The advantage for people is that they can stick to a version and then adapt to a new version (with a change potentially breaking their playbook) at their own pace.

Proposal for a versioning schema could be https://semver.org/

**Comment by michaelrigart** [comment]
Hey @layereight ,

sorry for the late intervention. I was on holiday and lost track of it when returning.

At what version number would you suggest to start? A 1.0.0 to mark the start from this day?

**Comment by markgoddard** [comment]
Sounds reasonable to me.

**Comment by layereight** [comment]
Sounds good to me as well. 1.0.0 is fine.

**Comment by layereight** [comment]
And?

**Comment by markgoddard** [comment]
Hooray! Version v1.0.0 is now released! I'll keep an eye on Galaxy to see if it gets reimported, or tagged, or something.

https://github.com/michaelrigart/ansible-role-interfaces/releases/tag/v1.0.0

**Comment by markgoddard** [comment]
I had to do a manual reimport of the role to make v1.0.0 the default version, but it does now seem to be.

```
$ sudo ansible-galaxy install MichaelRigart.interfaces 
- downloading role 'interfaces', owned by MichaelRigart
- downloading role from https://github.com/michaelrigart/ansible-role-interfaces/archive/v1.0.0.tar.gz
- extracting MichaelRigart.interfaces to /etc/ansible/roles/MichaelRigart.interfaces
- MichaelRigart.interfaces (v1.0.0) was installed successfully
```
