### ISSUE TITLE
dnsnameservers redhat?

### ISSUE THREAD

**Issue by cavamagie** [michaelrigart/ansible-role-interfaces#41]
in the redhat the dnsnameservers is not enabled??

**Comment by markgoddard** [comment]
Could you provide some more information?

**Comment by cavamagie** [comment]
yes srry you can use this kind of info

roles:
    - role: MichaelRigart.interfaces
      interfaces_ether_interfaces:
       - device: eth1
         bootproto: static
         address: 192.168.1.150
         netmask: 255.255.255.0
         gateway: 192.168.1.1
         dnsnameservers: 192.0.2.1 192.0.2.2
         dnssearch: example.com
         mtu: 9000
         route:
          - network: 192.168.200.0
            netmask: 255.255.255.0
            gateway: 192.168.1.1
          - network: 192.168.100.0
            netmask: 255.255.255.0
            gateway: 192.168.1.1
       - device: eth2
         bootproto: dhcp



and  dnsnameservers: 192.0.2.1 192.0.2.2 work in debian with resolvconf
but in redhat the value is not used in the configuration


 grep -r dnsnameservers *
README.md:         dnsnameservers: 192.0.2.1 192.0.2.2
README.md:         dnsnameservers: 192.0.2.1 192.0.2.2
README.md:          dnsnameservers: 192.168.1.1
templates/ethernet_Debian.j2:{% if item.dnsnameservers is defined %}
templates/ethernet_Debian.j2:dns-nameservers {{ item.dnsnameservers }}

**Comment by markgoddard** [comment]
Looks like you can set DNS1 and DNS2 in interface config files. Feel free to submit a PR.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-networkscripts-interfaces

**Comment by cavamagie** [comment]
ah ok we can add an

{% if item.dnsnameservers is defined %}
DNS={{ item.dnsnameservers }}
{% endif %}

to jnj file?

**Comment by markgoddard** [comment]
That might work for a single server, for two servers you would need to use DNS1 and DNS2. Try it out.

**Comment by cavamagie** [comment]
thanks @markgoddard 

{% if item.dnsnameservers is defined %}
{% if item.dnsnameservers.split(' ')[-2] is defined %}
DNS2={{ item.dnsnameservers.split(' ')[-2]}}
{% endif %}
{% if item.dnsnameservers.split(' ')[-1] is defined %}
DNS1={{ item.dnsnameservers.split(' ')[-1]}}
{% endif %}
{% else %}
DNS1=xxxxx
DNS2=xxxxx
{% endif %}

**Comment by markgoddard** [comment]
How about:

{% if item.dnsnameservers is defined %}
{% for dns_server in item.dnsnameservers.split(' ')[:2] %}
DNS{{ loop.index + 1 }}={{ dns_server }}
{% endfor %}
{% endif %}

**Comment by cavamagie** [comment]
thank you!
