### ISSUE TITLE
[DEPRECATION WARNING]: Using tests as filters is deprecated.

### ISSUE THREAD

**Issue by cavamagie** [michaelrigart/ansible-role-interfaces#44]
DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using 
`result|match` use `result is match`. This feature will be removed in version 
2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False
 in ansible.cfg.

**Comment by markgoddard** [comment]
2.9 is here, we didn't act, and we got bitten :)
